spring:
  config:
    activate:
      on-profile: "local"
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
server:
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 20MB
mybatis:
  mapper-locations:
    - mapper/*.xml

---
spring:
  config:
    active:
      on-profile: "local"
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/personal_schedule
    username: root
    password: root**3048
server:
  address: localhost
  port: 8030
  domain: http://${server.address}:${server.port}
jwt:
  secret: cGVyc29uYWxfc2NoZWR1bGVfc2VjcmV0X2tleQ==